Repository eunsolkang/review-analysis-web-report, pull requests merged in 2021-02, with the labels that each got.

#2 Create a Collaboration Guide
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/things_to_do.md
  .github/PULL_REQUEST_TEMPLATE.md
  collaborationGuide.md
Labels: docs

#12 Separate review data into sentences and label #6
  data/concatStrs.py
  data/crawling.py
  data/review_seperated_by_sentences1.csv
  data/review_seperated_by_sentences2.csv
  data/review_seperated_by_sentences3.csv
  data/review_seperated_by_sentences_conclusion.csv
Labels: data

#19 Develop trend crawl code
  data/concatNdistribute.py
  data/concatStrs.py
  data/crawlReview.py
  data/crawlTrend.js
Labels: data

#25 Add backend server code
  server/api/router.js
  server/api/swagger.yaml
  server/app.js
  server/bin/www.js
  server/config/environments.js
  server/package.json
  server/testcode/crawlReview.py
  server/testcode/crawlTrend.js
  server/testcode/wordCloudMaker.py
Labels: be

#27 :sparkles: features: Add mockup data(#23)
  server/api/product.js
  server/api/reviewAnalysis.js
  server/api/router.js
  server/api/trendAnalysis.js
  server/app.js
  server/tmpData/abcdefg_wordcloud.png
  server/tmpData/abcdefg_wordcloud_negative.png
  server/tmpData/abcdefg_wordcloud_positive.png
  server/tmpData/test.txt
Labels: be

#32 Add API function code #23
  server/api/product.js
  server/api/pyCode/crawlReview.py
  server/api/pyCode/labelReview.py
  server/api/pyCode/reviewScoreCount.py
  server/api/pyCode/wordCloudMaker.py
  server/api/reviewAnalysis.js
  server/api/swagger.yaml
  server/api/trendAnalysis.js
  server/package.json
Labels: be

#37 💾 data: Add tmpDatas (#36)
  server/tmpData/10da5800-7343-11eb-af2f-43a8e6ee612c-review_seperated_by_sentences.csv
  server/tmpData/10da5800-7343-11eb-af2f-43a8e6ee612c-review_seperated_by_sentences_labeled.csv
  server/tmpData/10da5800-7343-11eb-af2f-43a8e6ee612c-reviews.csv
  server/tmpData/2a04dc20-7333-11eb-ae9e-758a5443ae76-allWC.png
  server/tmpData/2a04dc20-7333-11eb-ae9e-758a5443ae76-conWC.png
  server/tmpData/2a04dc20-7333-11eb-ae9e-758a5443ae76-proWC.png
  server/tmpData/2a04dc20-7333-11eb-ae9e-758a5443ae76-review_seperated_by_sentences.csv
  server/tmpData/2a04dc20-7333-11eb-ae9e-758a5443ae76-review_seperated_by_sentences_labeled.csv
  server/tmpData/2a04dc20-7333-11eb-ae9e-758a5443ae76-reviews.csv
  server/tmpData/a034c420-732c-11eb-91c9-df22bc56a1db-review_seperated_by_sentences.csv
  server/tmpData/a034c420-732c-11eb-91c9-df22bc56a1db-review_seperated_by_sentences_labeled.csv
  server/tmpData/a034c420-732c-11eb-91c9-df22bc56a1db-reviews.csv
  server/tmpData/c7cc9fb0-7356-11eb-87c6-43d179a8e5c5-review_seperated_by_sentences.csv
  server/tmpData/c7cc9fb0-7356-11eb-87c6-43d179a8e5c5-review_seperated_by_sentences_labeled.csv
  server/tmpData/c7cc9fb0-7356-11eb-87c6-43d179a8e5c5-reviews.csv
  server/tmpData/f4131860-7342-11eb-a59d-23c5b7c83f1a-review_seperated_by_sentences.csv
  server/tmpData/f4131860-7342-11eb-a59d-23c5b7c83f1a-review_seperated_by_sentences_labeled.csv
  server/tmpData/f4131860-7342-11eb-a59d-23c5b7c83f1a-reviews.csv
Labels: data
